import { flushPromises, mount } from '@vue/test-utils'
import { createMemoryHistory, createRouter } from 'vue-router'
import { afterEach, describe, expect, it, vi } from 'vitest'
import AssetImagesWorkspace from './AssetImagesWorkspace.vue'
import * as projectApi from '@/features/projects/api'
import * as replicaApi from '@/features/projects/replicaFiveStep'

vi.mock('@/features/projects/api',()=>({listProjectTasks:vi.fn()}))
vi.mock('@/features/projects/replicaFiveStep',()=>({getAssetWorkspace:vi.fn(),getLocalizedStoryboard:vi.fn(),extractAssetWorkspace:vi.fn(),generateAssetPrompts:vi.fn(),generateAssetImages:vi.fn()}))
const empty={project_id:'project-1',status:'EMPTY' as const,revision:null,content:null}
const ready={project_id:'project-1',status:'READY' as const,revision:1,content:{target_storyboard_artifact_id:'story-1',target_language:'en-US',target_region:'US',visual_style:'写实',assets:[{target_asset_id:'asset-1',asset_type:'CHARACTER' as const,target_entity_id:'char-1',display_name:'Riley',review_description_zh:'年轻女性',width:1536,height:768,image_prompt:null,negative_prompt:'',prompt_review_zh:null,image_model_id:null,prompt_skill_id:null,prompt_skill_version:null,prompt_contract:null,active_generation_id:null,generations:[]}]}}
async function mounted(){const router=createRouter({history:createMemoryHistory(),routes:[{path:'/projects/:id',component:{template:'<main/>'}}]});await router.push('/projects/project-1');await router.isReady();const wrapper=mount(AssetImagesWorkspace,{global:{plugins:[router]}});await flushPromises();return wrapper}
afterEach(()=>vi.clearAllMocks())
describe('AssetImagesWorkspace staged workflow',()=>{
  it('starts blank and extracts entities only after explicit click',async()=>{vi.mocked(replicaApi.getAssetWorkspace).mockResolvedValue(empty);vi.mocked(replicaApi.getLocalizedStoryboard).mockResolvedValue({project_id:'project-1',status:'CURRENT',artifact_id:'story-1',revision:1,content:null});vi.mocked(projectApi.listProjectTasks).mockResolvedValue([]);vi.mocked(replicaApi.extractAssetWorkspace).mockResolvedValue(ready);const wrapper=await mounted();expect(wrapper.text()).toContain('还没有提取视觉资产');await wrapper.get('.blank button').trigger('click');await flushPromises();expect(replicaApi.extractAssetWorkspace).toHaveBeenCalledWith('project-1');expect(wrapper.text()).toContain('Riley');wrapper.unmount()})
  it('selects assets and starts Prompt Skill separately from image generation',async()=>{vi.mocked(replicaApi.getAssetWorkspace).mockResolvedValue(ready);vi.mocked(replicaApi.getLocalizedStoryboard).mockResolvedValue({project_id:'project-1',status:'CURRENT',artifact_id:'story-1',revision:1,content:null});vi.mocked(projectApi.listProjectTasks).mockResolvedValue([]);vi.mocked(replicaApi.generateAssetPrompts).mockResolvedValue({id:'task-1',project_id:'project-1',task_type:'replica.asset-prompts',task_name:'生成资产提示词',progress_percent:0,status:'queued',last_error:null,attempt:0,max_attempts:3,can_retry:false,can_cancel:true,can_resume:false,created_at:'2026-09-17T00:00:00Z',started_at:null,finished_at:null});const wrapper=await mounted();await wrapper.get('.check').trigger('click');await wrapper.findAll('.actions button').find(x=>x.text()==='生成提示词')!.trigger('click');await flushPromises();expect(replicaApi.generateAssetPrompts).toHaveBeenCalledWith('project-1',['asset-1']);expect(replicaApi.generateAssetImages).not.toHaveBeenCalled();wrapper.unmount()})
})
