from enum import StrEnum

from pydantic import BaseModel

from app.projects.enums import ProjectType


class Capability(StrEnum):
    SOURCE_VIDEO_INGEST = "SOURCE_VIDEO_INGEST"
    SOURCE_TEXT_INGEST = "SOURCE_TEXT_INGEST"
    MEDIA_PREFLIGHT = "MEDIA_PREFLIGHT"
    SHOT_BOUNDARY = "SHOT_BOUNDARY"
    SOURCE_DIALOGUE_EVIDENCE = "SOURCE_DIALOGUE_EVIDENCE"
    EPISODE_UNDERSTANDING = "EPISODE_UNDERSTANDING"
    STORY_RHYTHM = "STORY_RHYTHM"
    SHOT_BREAKDOWN = "SHOT_BREAKDOWN"
    IDENTITY_RESOLUTION = "IDENTITY_RESOLUTION"
    SCENE_RESOLUTION = "SCENE_RESOLUTION"
    PROP_RESOLUTION = "PROP_RESOLUTION"
    SOURCE_SNAPSHOT = "SOURCE_SNAPSHOT"
    SCRIPT_ANALYSIS = "SCRIPT_ANALYSIS"
    NOVEL_ADAPTATION = "NOVEL_ADAPTATION"
    LOCALIZATION = "LOCALIZATION"
    TARGET_BIBLE = "TARGET_BIBLE"
    TARGET_SCRIPT = "TARGET_SCRIPT"
    TARGET_ASSETS = "TARGET_ASSETS"
    TTS = "TTS"
    TIMING = "TIMING"
    STORYBOARD = "STORYBOARD"
    VIDEO_GENERATION = "VIDEO_GENERATION"
    QC_SELECTION = "QC_SELECTION"
    LIP_SYNC = "LIP_SYNC"
    POST_PRODUCTION = "POST_PRODUCTION"
    EXPORT_SCRIPT = "EXPORT_SCRIPT"


class ArtifactType(StrEnum):
    SOURCE_VIDEO = "SOURCE_VIDEO"
    SOURCE_TEXT = "SOURCE_TEXT"
    SHOT_ANCHORS = "SHOT_ANCHORS"
    SOURCE_DIALOGUE = "SOURCE_DIALOGUE"
    SOURCE_BIBLE = "SOURCE_BIBLE"
    STORY_SKELETON = "STORY_SKELETON"
    RHYTHM_SKELETON = "RHYTHM_SKELETON"
    SOURCE_SHOT_FACTS = "SOURCE_SHOT_FACTS"
    SOURCE_CHARACTERS = "SOURCE_CHARACTERS"
    SOURCE_SCENES = "SOURCE_SCENES"
    SOURCE_PROPS = "SOURCE_PROPS"
    SOURCE_VIDEO_SNAPSHOT = "SOURCE_VIDEO_SNAPSHOT"
    SOURCE_TEXT_SNAPSHOT = "SOURCE_TEXT_SNAPSHOT"
    ADAPTATION_PLAN = "ADAPTATION_PLAN"
    TARGET_BIBLE = "TARGET_BIBLE"
    TARGET_SCRIPT = "TARGET_SCRIPT"
    TARGET_ASSETS = "TARGET_ASSETS"
    TARGET_AUDIO = "TARGET_AUDIO"
    TIMING_PLAN = "TIMING_PLAN"
    TARGET_STORYBOARD = "TARGET_STORYBOARD"
    GENERATION_SEGMENTS = "GENERATION_SEGMENTS"
    GENERATED_VIDEO = "GENERATED_VIDEO"
    GENERATION_SELECTION = "GENERATION_SELECTION"
    FINAL_OUTPUT = "FINAL_OUTPUT"


class CapabilityDefinition(BaseModel):
    id: Capability
    title: str
    description: str
    category: str


class SkillStepDefinition(BaseModel):
    id: str
    phase: str
    title: str
    description: str
    capabilities: tuple[Capability, ...]
    requires: tuple[ArtifactType, ...] = ()
    produces: tuple[ArtifactType, ...] = ()


class RootSkillDefinition(BaseModel):
    id: str
    project_type: ProjectType
    title: str
    purpose: str
    manual_path: str
    steps: tuple[SkillStepDefinition, ...]


class RootSkillDetail(RootSkillDefinition):
    manual: str
