import { createApp } from 'vue'
import App from './App.vue'
import { router } from './router'
import './styles.css'
import './studio-v3.css'
import './f05.css'
import './shot-manager.css'
import './shot-revision.css'
import './shot-workbench-v3.css'
import './shot-workbench-v3-overrides.css'
import './shot-workbench-v4.css'
import './asset-workbench-v3.css'
import './asset-review-matrix-v4.css'
import './asset-review-matrix-v4-overrides.css'
import './asset-image-lightbox.css'
import './asset-image-lightbox'
import './task-progress.css'
import './breakdown-p3-acceptance.css'
import './breakdown-p3-v2-layout-fix.css'
import './breakdown-p3-v2-polish.css'
import './scene-timeline-g2-6-overrides.css'
import './product-readability.css'
import './source-video-page-fixes.css'
import './source-video-breakdown-navigation.css'
import './source-video-breakdown-navigation'
import './project-breakdown-shell-sync.css'
import './project-breakdown-shell-consistency.css'
import './project-breakdown-shell-consistency'
import './workflow-stage-shell.css'
import './source-video-error-dialog'
import './source-video-help-drawer.css'
import './source-video-help-drawer'

createApp(App).use(router).mount('#app')
