import { createApp } from 'vue'
import App from './App.vue'
import { router } from './router'
import './styles.css'
import './studio-v3.css'
import './f05.css'
import './shot-manager.css'
import './shot-revision.css'
import './shot-workbench-v3.css'
import './shot-workbench-v3-overrides.css'
import './shot-workbench-v4.css'
import './asset-workbench-v3.css'
import './asset-review-matrix-v4.css'
import './asset-review-matrix-v4-overrides.css'
import './asset-image-lightbox.css'
import './asset-image-lightbox'
import './task-progress.css'

createApp(App).use(router).mount('#app')
