#!/usr/bin/env python3
"""Compact Exact-Shot grounding contract v2 for Fast Grounded Breakdown.

The legacy Exact-Shot prompt returns a verbose canonical semantic object for every Shot. Real
instrumentation on the reference Episode showed ~2.2k-2.4k generated tokens per 5-Shot batch even
though the 4096-token cap was not reached. This candidate keeps the visual facts actually needed by
G1 while moving deterministic compatibility fields back to Python.

The model uses batch-local 1-based Shot indexes only. Frozen revision_item_id values and canonical
subject_A/B labels are never generated by the model; the adapter restores them from the manifest and
per-Shot subject order. Exact-Shot images remain the only source for visible people/actions/props.
"""
from __future__ import annotations

from pathlib import Path
import sys
from typing import Any, Mapping, Sequence

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import run_breakdown_vlm_fast_grounded_qwen3 as fast

EXACT_SHOT_PROMPT_PROFILE = "breakdown-p2-vlm-exact-shot-compact-zh-v2"
_ALLOWED_IE = {"INT", "EXT", "MIXED", "UNKNOWN"}
_ALLOWED_VISIBILITY = {"FULL", "PARTIAL", "OCCLUDED", "BACK_VIEW", "UNKNOWN"}
_ALLOWED_IMPORTANCE = {"LOW", "MEDIUM", "HIGH"}


def _clean(value: Any, limit: int) -> str:
    return " ".join(str(value or "").strip().split())[:limit]


def _subject_label(index: int) -> str:
    if 1 <= index <= 26:
        return f"subject_{chr(ord('A') + index - 1)}"
    return f"subject_{index}"


def _compact_scene_contexts(
    batch: Sequence[Mapping[str, Any]],
    windows: Sequence[Mapping[str, Any]],
    window_results: Mapping[str, Mapping[str, Any]],
) -> list[dict[str, Any]]:
    canonical = fast._grounding_scene_contexts(batch, windows, window_results)
    rows: list[dict[str, Any]] = []
    for local_index, shot in enumerate(batch, start=1):
        item_id = str(shot.get("revision_item_id") or "").strip()
        contexts: list[dict[str, Any]] = []
        for raw in canonical.get(item_id, []):
            if not isinstance(raw, Mapping):
                continue
            hint = raw.get("shot_scene_hint")
            if not isinstance(hint, Mapping):
                continue
            scene = hint.get("scene") if isinstance(hint.get("scene"), Mapping) else {}
            compact = {
                "loc": _clean(scene.get("location_hint"), 40),
                "ie": str(scene.get("interior_exterior") or "UNKNOWN").strip().upper(),
                "tod": _clean(scene.get("time_of_day"), 16),
            }
            if compact not in contexts:
                contexts.append(compact)
        rows.append({"i": local_index, "scene_ctx": contexts[:2]})
    return rows


def _prompt(
    source_language: str,
    batch: Sequence[Mapping[str, Any]],
    scene_contexts: Sequence[Mapping[str, Any]],
) -> str:
    import json

    language = (source_language or "und").strip() or "und"
    targets = ", ".join(
        f"{index}=EpisodeShot{fast._safe_int(shot.get('ordinal'))}"
        for index, shot in enumerate(batch, start=1)
    )
    context_json = json.dumps(scene_contexts, ensure_ascii=False, separators=(",", ":"))
    return f"""你是短剧 Exact-Shot 视觉事实提取器。原始语言：{language}。
只输出一个合法 JSON object，不要 Markdown、解释、额外字段。

本批 ShotIndex：{targets}
Scene上下文（只可补地点/INT-EXT/时间，不能搬入邻镜人物动作道具）：{context_json}

随后图片按 ShotIndex 分组；每组图片只属于该 Shot。

硬规则：
1. visible / people / props / shot_type / composition 只能来自当前 Shot 图片。
2. 当前 Shot 看不到的人、动作、道具绝不能从上下文补入。
3. 不猜姓名、Character/Scene/Prop ID；people 按当前 Shot 稳定视觉顺序输出。
4. 不转录对白/OCR；说话真相由 ASR 负责。
5. 静态采样图不能可靠判断推/拉/摇/移，因此不要输出 camera motion；程序统一记 UNKNOWN。
6. visible<=80字；appearance<=32字；activity<=24字；composition<=24字；interaction<=20字。
7. 每个 ShotIndex 必须且只能输出一次。不要输出 revision_item_id、subject_A/B、events、长解释。

JSON schema：
{{
  "shots":[{{
    "i":1,
    "scene":{{"loc":"地点或空","ie":"INT|EXT|MIXED|UNKNOWN","tod":"白天|夜晚|未知"}},
    "visible":"当前Shot核心可见事实",
    "shot_type":"特写|近景|中景|全景|远景|空",
    "composition":"简短构图或空",
    "people":[{{
      "appearance":"稳定可见外观",
      "activity":"当前可见动作",
      "position":"左侧|中央|右侧|前景|背景|UNKNOWN",
      "visibility":"FULL|PARTIAL|OCCLUDED|BACK_VIEW|UNKNOWN"
    }}],
    "props":[{{
      "label":"可见剧情道具",
      "importance":"LOW|MEDIUM|HIGH",
      "people":[1],
      "interaction":"与人物的可见关系或空"
    }}]
  }}]
}}
"""


def _messages(
    *,
    source_language: str,
    batch: Sequence[Mapping[str, Any]],
    scene_contexts: Sequence[Mapping[str, Any]],
    max_pixels: int,
) -> list[dict[str, Any]]:
    content: list[dict[str, Any]] = [{
        "type": "text",
        "text": _prompt(source_language, batch, scene_contexts),
    }]
    for local_index, shot in enumerate(batch, start=1):
        ordinal = fast._safe_int(shot.get("ordinal"))
        content.append({"type": "text", "text": f"ShotIndex {local_index} / EpisodeShot {ordinal}"})
        frames = shot.get("frames")
        if not isinstance(frames, list) or not frames:
            raise ValueError(f"Shot {ordinal} has no grounding frames")
        for frame_index, raw in enumerate(frames, start=1):
            if not isinstance(raw, Mapping):
                continue
            path = Path(str(raw.get("path") or ""))
            if not path.is_file():
                raise FileNotFoundError(f"Shot {ordinal} frame missing")
            content.append({"type": "text", "text": f"ShotIndex {local_index} frame {frame_index}"})
            content.append({
                "type": "image",
                "image": fast._media_ref(path),
                "max_pixels": int(max_pixels),
            })
    return [{"role": "user", "content": content}]


def _canonical_subjects(raw: Any) -> list[dict[str, Any]]:
    if not isinstance(raw, list):
        return []
    result: list[dict[str, Any]] = []
    for index, item in enumerate(raw[:12], start=1):
        if not isinstance(item, Mapping):
            continue
        visibility = str(item.get("visibility") or "UNKNOWN").strip().upper()
        if visibility not in _ALLOWED_VISIBILITY:
            visibility = "UNKNOWN"
        result.append({
            "label": _subject_label(index),
            "appearance_summary": _clean(item.get("appearance"), 160),
            "activity_summary": _clean(item.get("activity"), 160),
            "screen_position": _clean(item.get("position"), 48) or "UNKNOWN",
            "visibility": visibility,
            "speaking_state": "UNKNOWN",
        })
    return result


def _canonical_props(raw: Any, subject_count: int) -> list[dict[str, Any]]:
    if not isinstance(raw, list):
        return []
    result: list[dict[str, Any]] = []
    seen: set[str] = set()
    for item in raw[:12]:
        if not isinstance(item, Mapping):
            continue
        label = _clean(item.get("label"), 160)
        marker = label.casefold()
        if not label or marker in seen:
            continue
        seen.add(marker)
        importance = str(item.get("importance") or "LOW").strip().upper()
        if importance not in _ALLOWED_IMPORTANCE:
            importance = "LOW"
        labels: list[str] = []
        indexes = item.get("people")
        if isinstance(indexes, list):
            for raw_index in indexes:
                try:
                    index = int(raw_index)
                except (TypeError, ValueError):
                    continue
                if 1 <= index <= subject_count:
                    label_key = _subject_label(index)
                    if label_key not in labels:
                        labels.append(label_key)
        result.append({
            "label": label,
            "importance": importance,
            "narrative_reason": _clean(item.get("interaction"), 160),
            "subject_labels": labels,
        })
    return result


def expand_compact(value: Mapping[str, Any], batch: Sequence[Mapping[str, Any]]) -> list[dict[str, Any]]:
    """Expand compact local-index output into the canonical exact-Shot semantic contract."""

    raw_shots = value.get("shots")
    if not isinstance(raw_shots, list):
        raise ValueError("compact exact-shot output.shots must be a list")
    by_index: dict[int, Mapping[str, Any]] = {}
    for raw in raw_shots:
        if not isinstance(raw, Mapping):
            continue
        index = fast._safe_int(raw.get("i"))
        if index < 1 or index > len(batch) or index in by_index:
            raise ValueError("compact exact-shot output has invalid/duplicate ShotIndex")
        by_index[index] = raw
    if set(by_index) != set(range(1, len(batch) + 1)):
        raise ValueError("compact exact-shot output must cover every target ShotIndex exactly once")

    result: list[dict[str, Any]] = []
    for index, target in enumerate(batch, start=1):
        raw = by_index[index]
        item_id = str(target.get("revision_item_id") or "").strip()
        if not item_id:
            raise ValueError("compact exact-shot target missing revision_item_id")
        scene_raw = raw.get("scene") if isinstance(raw.get("scene"), Mapping) else {}
        ie = str(scene_raw.get("ie") or "UNKNOWN").strip().upper()
        if ie not in _ALLOWED_IE:
            ie = "UNKNOWN"
        visible = _clean(raw.get("visible"), 1200)
        if not visible:
            raise ValueError("compact exact-shot visible description is required")
        subjects = _canonical_subjects(raw.get("people"))
        props = _canonical_props(raw.get("props"), len(subjects))
        semantic = {
            "scene": {
                "location_hint": _clean(scene_raw.get("loc"), 255),
                "interior_exterior": ie,
                "time_of_day": _clean(scene_raw.get("tod"), 64) or "未知",
                "environment_description": "",
            },
            "shot": {
                "summary": visible,
                "visual_description": visible,
                "shot_type_hint": _clean(raw.get("shot_type"), 64),
                "camera_motion_hint": "UNKNOWN",
                "narrative_function_hint": "",
                "composition_hint": _clean(raw.get("composition"), 160),
            },
            "subjects": subjects,
            "events": [],
            "props": props,
        }
        result.append({"revision_item_id": item_id, "semantic": semantic})
    return result


def analyze_grounding_batch(
    *,
    model: Any,
    processor: Any,
    batch: Sequence[Mapping[str, Any]],
    source_language: str,
    windows: Sequence[Mapping[str, Any]],
    window_results: Mapping[str, Mapping[str, Any]],
    max_pixels: int,
    max_new_tokens: int,
) -> list[dict[str, Any]]:
    contexts = _compact_scene_contexts(batch, windows, window_results)
    value = fast._generate_json(
        model=model,
        processor=processor,
        messages=_messages(
            source_language=source_language,
            batch=batch,
            scene_contexts=contexts,
            max_pixels=max_pixels,
        ),
        max_new_tokens=max_new_tokens,
    )
    return expand_compact(value, batch)


def grounding_adaptive(
    *,
    model: Any,
    processor: Any,
    batch: Sequence[Mapping[str, Any]],
    source_language: str,
    windows: Sequence[Mapping[str, Any]],
    window_results: Mapping[str, Mapping[str, Any]],
    max_pixels: int,
    max_new_tokens: int,
) -> list[dict[str, Any]]:
    targets = tuple(batch)
    try:
        return analyze_grounding_batch(
            model=model,
            processor=processor,
            batch=targets,
            source_language=source_language,
            windows=windows,
            window_results=window_results,
            max_pixels=max_pixels,
            max_new_tokens=max_new_tokens,
        )
    except Exception:
        if len(targets) <= 1:
            raise
        midpoint = max(1, len(targets) // 2)
        left = grounding_adaptive(
            model=model,
            processor=processor,
            batch=targets[:midpoint],
            source_language=source_language,
            windows=windows,
            window_results=window_results,
            max_pixels=max_pixels,
            max_new_tokens=max_new_tokens,
        )
        fast._cleanup_cuda()
        right = grounding_adaptive(
            model=model,
            processor=processor,
            batch=targets[midpoint:],
            source_language=source_language,
            windows=windows,
            window_results=window_results,
            max_pixels=max_pixels,
            max_new_tokens=max_new_tokens,
        )
        return [*left, *right]


__all__ = [
    "EXACT_SHOT_PROMPT_PROFILE",
    "_prompt",
    "analyze_grounding_batch",
    "expand_compact",
    "grounding_adaptive",
]
