"""Grounded source-screenplay reconstruction and derived-artifact storage.

V2 fixes the main V1 product problem: episode understanding must visibly affect the
screenplay instead of merely attaching story-beat refs to a deterministic Shot dump.

Safety boundary:
- SourceDramaSnapshot remains immutable source truth.
- The model may only organize/condense ACTION prose using current source refs.
- Canonical source dialogue text and speakers are never generated by the model.
- Every canonical SourceDialogueUtterance is inserted exactly once by deterministic code.
- GET/read paths only load a materialized derived artifact and never execute a model.
"""
from __future__ import annotations

import json
import os
from collections.abc import Callable, Mapping
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from engine.app import studio_v2
from engine.app.local_qwen_text_v1 import request_local_qwen_json
from engine.app.source_drama_snapshot_contract_v1 import SourceDramaEpisodeSnapshotV1
from engine.app.source_story_skills_v1 import (
    SCREENPLAY_RECONSTRUCTION_SKILL,
    EpisodeUnderstandingV1,
    RuntimeSkillRefV1,
    ScreenplayActionV1,
    ScreenplayDialogueV1,
    ScreenplayReconstructionV1,
    ScreenplaySceneV1,
    ShotFactsEpisodeV1,
    SourceScreenplayCompilationV1,
    SourceStorySkillError,
    compile_episode_understanding_v1,
    compile_shot_facts_v1,
)
from engine.skills.registry import validate_runtime_skill_ref

SOURCE_SCREENPLAY_ARTIFACT_FILENAME = "source-screenplay-compilation-v1.json"


class _StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class ScreenplayPlanActionV1(_StrictModel):
    kind: Literal["ACTION"] = "ACTION"
    text: str = Field(min_length=1)
    supporting_fact_refs: list[str] = Field(min_length=1)


class ScreenplayPlanDialogueV1(_StrictModel):
    kind: Literal["DIALOGUE"] = "DIALOGUE"
    dialogue_group_id: str = Field(min_length=1)


class ScreenplayPlanSceneV1(_StrictModel):
    scene_key: str = Field(min_length=1)
    blocks: list[ScreenplayPlanActionV1 | ScreenplayPlanDialogueV1] = Field(min_length=1)


class ScreenplayPlanCandidateV1(_StrictModel):
    scenes: list[ScreenplayPlanSceneV1] = Field(min_length=1)
    unresolved: list[str] = Field(default_factory=list)


class SourceScreenplayReadV1(_StrictModel):
    state: Literal["MISSING", "READY", "STALE"]
    episode_id: str
    source_fingerprint: str = Field(pattern=r"^[0-9a-f]{64}$")
    message: str
    compilation: SourceScreenplayCompilationV1 | None = None


def _skill_ref() -> RuntimeSkillRefV1:
    contract = validate_runtime_skill_ref(
        *SCREENPLAY_RECONSTRUCTION_SKILL,
        require_runtime_ready=True,
    )
    return RuntimeSkillRefV1(id=contract.skill_id, version=contract.version)


def _scene_heading(scene: Any) -> str:
    info = scene.scene_info
    space = (info.interior_exterior or "").strip().lower()
    if "内" in space or "int" in space:
        prefix = "INT."
    elif "外" in space or "ext" in space:
        prefix = "EXT."
    else:
        prefix = "SCENE"
    place = scene.final_scene.name if scene.final_scene is not None else (info.location or scene.title)
    time_of_day = (info.time_of_day or "").strip()
    return f"{prefix} {place}" + (f" - {time_of_day}" if time_of_day else "")


def _format_time(us: int) -> str:
    total_ms = max(0, int(us)) // 1000
    total_seconds, millis = divmod(total_ms, 1000)
    minutes, seconds = divmod(total_seconds, 60)
    hours, minutes = divmod(minutes, 60)
    if hours:
        return f"{hours:02d}:{minutes:02d}:{seconds:02d}.{millis:03d}"
    return f"{minutes:02d}:{seconds:02d}.{millis:03d}"


def _person_name_map(snapshot: SourceDramaEpisodeSnapshotV1) -> dict[str, str]:
    names: dict[str, str] = {}
    for scene in snapshot.scenes:
        for person in scene.people:
            name = person.character.name if person.character is not None else person.display_name
            names.setdefault(person.person_key, name)
    return names


def _screenplay_packet(
    snapshot: SourceDramaEpisodeSnapshotV1,
    shot_facts: ShotFactsEpisodeV1,
    understanding: EpisodeUnderstandingV1,
) -> tuple[dict[str, Any], set[str], list[str], list[str]]:
    person_names = _person_name_map(snapshot)
    fact_by_shot = {shot.shot_key: shot for shot in shot_facts.shots}
    allowed_refs: set[str] = set()
    scene_keys: list[str] = []
    scenes: list[dict[str, Any]] = []

    beats_by_scene: dict[str, list[dict[str, Any]]] = {scene.scene_key: [] for scene in snapshot.scenes}
    shot_to_scene = {
        shot.shot_key: scene.scene_key
        for scene in snapshot.scenes
        for shot in scene.shots
    }
    for beat in understanding.story_beats:
        for scene_key in dict.fromkeys(shot_to_scene[key] for key in beat.shot_keys if key in shot_to_scene):
            beats_by_scene.setdefault(scene_key, []).append(beat.model_dump(mode="json"))

    utterances_by_scene: dict[str, list[dict[str, Any]]] = {scene.scene_key: [] for scene in snapshot.scenes}
    dialogue_ids: list[str] = []
    for utterance in sorted(snapshot.source_dialogue_utterances, key=lambda row: (row.start_us, row.dialogue_group_id)):
        first_scene = utterance.projections[0].scene_key
        ref = f"utterance:{utterance.dialogue_group_id}"
        allowed_refs.add(ref)
        dialogue_ids.append(utterance.dialogue_group_id)
        utterances_by_scene.setdefault(first_scene, []).append({
            "ref": ref,
            "dialogue_group_id": utterance.dialogue_group_id,
            "start_us": utterance.start_us,
            "end_us": utterance.end_us,
            "speaker_names": [person_names.get(key, key) for key in utterance.speakers],
            "source_text": utterance.source_text,
            "shot_keys": [projection.shot_key for projection in utterance.projections],
        })

    for scene in snapshot.scenes:
        scene_keys.append(scene.scene_key)
        scene_ref = f"scene:{scene.scene_key}"
        allowed_refs.add(scene_ref)
        shot_rows: list[dict[str, Any]] = []
        for shot in scene.shots:
            fact = fact_by_shot.get(shot.shot_key)
            if fact is None:
                raise SourceStorySkillError(f"shot_facts is missing current Shot {shot.shot_key}")
            shot_ref = f"shot:{shot.shot_key}"
            allowed_refs.add(shot_ref)
            shot_rows.append({
                "ref": shot_ref,
                "shot_key": shot.shot_key,
                "start_us": shot.start_us,
                "end_us": shot.end_us,
                "visual_description": fact.facts.get("visual_description"),
                "subjects": fact.facts.get("subjects") or [],
                "actions": fact.facts.get("actions") or [],
                "expressions": fact.facts.get("expressions") or [],
                "interactions": fact.facts.get("interactions") or [],
                "props": fact.facts.get("props") or {},
            })
        scene_block = next(
            (block.model_dump(mode="json") for block in understanding.scene_blocks if set(block.shot_keys).intersection({shot.shot_key for shot in scene.shots})),
            None,
        )
        scenes.append({
            "ref": scene_ref,
            "scene_key": scene.scene_key,
            "heading": _scene_heading(scene),
            "source_title": scene.title,
            "source_story_summary": scene.story_summary,
            "scene_info": scene.scene_info.model_dump(mode="json"),
            "understanding": scene_block,
            "story_beats": beats_by_scene.get(scene.scene_key, []),
            "shots": shot_rows,
            "utterances": utterances_by_scene.get(scene.scene_key, []),
        })

    packet = {
        "episode_id": snapshot.episode_id,
        "episode_title": snapshot.episode_title,
        "source_language": snapshot.source_language,
        "episode_summary": understanding.episode_summary,
        "scenes": scenes,
    }
    return packet, allowed_refs, scene_keys, dialogue_ids


def _screenplay_prompt(packet: Mapping[str, Any]) -> str:
    serialized = json.dumps(packet, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return f"""你是专业短剧编剧助理，任务是把已经确认的原片事实整理成“原片还原剧本”。

你不是创作者。你只能组织输入里已经存在的事实，让最终文本从“逐镜技术描述”变成真正可读的剧本。

目标风格：
- 按 Scene 写，不按 Shot 逐条复读。
- ACTION 要像专业剧本动作段落：简洁、连贯、可视化；可以把相邻镜头的重复描述合并。
- 保留影响剧情的人物动作、反应、关键道具和信息揭露；纯粹重复的机位/景别/构图无需写进 ACTION。
- DIALOGUE 只负责决定完整对白在动作之间的正确位置，不得生成、改写、缩写或补充任何对白正文。
- 结果必须让用户明显感觉是在读“剧本”，而不是在读 Shot 分析报告。

硬规则：
1. 不新增输入中不存在的人物、关系、动作、事件、道具、地点、心理事实或结局。
2. ACTION 每一条都必须提供 supporting_fact_refs，且只能引用输入里的 scene:/shot:/utterance: ref。
3. DIALOGUE block 只输出 dialogue_group_id，不允许输出 dialogue text；正式对白由程序从 SourceDialogueUtterance 原样插入。
4. 输入中的每一个 dialogue_group_id 必须在整份计划中恰好出现一次，不得遗漏、重复或拆分。
5. scenes 必须与输入 Scene 顺序完全一致，每个 scene_key 恰好一次。
6. 不要为了“完整”重复每个 Shot；允许把连续镜头合并为一条准确的 ACTION。
7. 不写 Camera、shot_type、构图、技术参数，除非它本身承担明确剧情信息且能用 source ref 支持。
8. 不做目标国家改编，不翻译，不润色正式对白。
9. episode_understanding 只帮助你理解哪些动作/反应重要；它不能授权你创造新事实。
10. 只输出一个 JSON object，不要 Markdown。

固定输出格式：
{{
  "scenes": [
    {{
      "scene_key": "SCENE_...",
      "blocks": [
        {{"kind":"ACTION","text":"简洁的剧本动作段落。","supporting_fact_refs":["shot:..."]}},
        {{"kind":"DIALOGUE","dialogue_group_id":"..."}}
      ]
    }}
  ],
  "unresolved": []
}}

<SOURCE_FACTS>{serialized}</SOURCE_FACTS>"""


def _validate_plan(
    plan: ScreenplayPlanCandidateV1,
    *,
    allowed_refs: set[str],
    scene_keys: list[str],
    dialogue_ids: list[str],
    snapshot: SourceDramaEpisodeSnapshotV1,
) -> None:
    actual_scene_keys = [scene.scene_key for scene in plan.scenes]
    if actual_scene_keys != scene_keys:
        raise SourceStorySkillError("screenplay_reconstruction scenes must match current source Scene order exactly")

    expected_dialogues = list(dialogue_ids)
    actual_dialogues = [
        block.dialogue_group_id
        for scene in plan.scenes
        for block in scene.blocks
        if isinstance(block, ScreenplayPlanDialogueV1)
    ]
    if sorted(actual_dialogues) != sorted(expected_dialogues) or len(actual_dialogues) != len(expected_dialogues):
        raise SourceStorySkillError("screenplay_reconstruction must reference every canonical dialogue exactly once")

    utterance_scene = {
        utterance.dialogue_group_id: utterance.projections[0].scene_key
        for utterance in snapshot.source_dialogue_utterances
    }
    for scene in plan.scenes:
        for block in scene.blocks:
            if isinstance(block, ScreenplayPlanActionV1):
                unknown = sorted(set(block.supporting_fact_refs) - allowed_refs)
                if unknown:
                    raise SourceStorySkillError("screenplay_reconstruction action references unknown source facts")
                if not any(ref.startswith("shot:") or ref.startswith("scene:") for ref in block.supporting_fact_refs):
                    raise SourceStorySkillError("screenplay_reconstruction action must be grounded in a current Scene/Shot")
            else:
                expected_scene = utterance_scene.get(block.dialogue_group_id)
                if expected_scene != scene.scene_key:
                    raise SourceStorySkillError("screenplay_reconstruction moved a canonical dialogue into another Scene")


def _ref_time(refs: list[str], snapshot: SourceDramaEpisodeSnapshotV1) -> int:
    shot_times = {
        f"shot:{shot.shot_key}": shot.start_us
        for scene in snapshot.scenes
        for shot in scene.shots
    }
    scene_times = {f"scene:{scene.scene_key}": scene.start_us for scene in snapshot.scenes}
    times = [shot_times[ref] for ref in refs if ref in shot_times]
    times.extend(scene_times[ref] for ref in refs if ref in scene_times)
    return min(times) if times else 0


def _dialogue_row(
    utterance: Any,
    *,
    person_names: Mapping[str, str],
) -> ScreenplayDialogueV1:
    names = [person_names.get(key, key) for key in utterance.speakers]
    speaker = " / ".join(dict.fromkeys(names)) if names else "未确认说话人"
    refs = [f"utterance:{utterance.dialogue_group_id}"]
    refs.extend(f"shot:{projection.shot_key}" for projection in utterance.projections)
    return ScreenplayDialogueV1(
        dialogue_group_id=utterance.dialogue_group_id,
        speaker=speaker,
        text=utterance.source_text,
        start_us=utterance.start_us,
        end_us=utterance.end_us,
        source_refs=list(dict.fromkeys(refs)),
    )


def compile_grounded_screenplay_reconstruction_v2(
    snapshot_payload: Mapping[str, Any] | SourceDramaEpisodeSnapshotV1,
    shot_facts: ShotFactsEpisodeV1,
    understanding: EpisodeUnderstandingV1,
    *,
    provider: Callable[[str], Mapping[str, Any]] | None = None,
) -> ScreenplayReconstructionV1:
    snapshot = (
        snapshot_payload
        if isinstance(snapshot_payload, SourceDramaEpisodeSnapshotV1)
        else SourceDramaEpisodeSnapshotV1.model_validate(snapshot_payload)
    )
    if shot_facts.source_fingerprint != snapshot.source_fingerprint:
        raise SourceStorySkillError("shot_facts is stale for screenplay reconstruction")
    if understanding.source_fingerprint != snapshot.source_fingerprint:
        raise SourceStorySkillError("episode_understanding is stale for screenplay reconstruction")

    packet, allowed_refs, scene_keys, dialogue_ids = _screenplay_packet(snapshot, shot_facts, understanding)
    raw = dict((provider or request_local_qwen_json)(_screenplay_prompt(packet)))
    try:
        plan = ScreenplayPlanCandidateV1.model_validate(raw)
    except ValidationError as exc:
        raise SourceStorySkillError("screenplay_reconstruction returned an invalid plan contract") from exc
    _validate_plan(
        plan,
        allowed_refs=allowed_refs,
        scene_keys=scene_keys,
        dialogue_ids=dialogue_ids,
        snapshot=snapshot,
    )

    person_names = _person_name_map(snapshot)
    utterance_by_id = {item.dialogue_group_id: item for item in snapshot.source_dialogue_utterances}
    scene_by_key = {scene.scene_key: scene for scene in snapshot.scenes}
    beats_by_scene: dict[str, list[str]] = {scene.scene_key: [] for scene in snapshot.scenes}
    shot_to_scene = {shot.shot_key: scene.scene_key for scene in snapshot.scenes for shot in scene.shots}
    for beat in understanding.story_beats:
        for scene_key in dict.fromkeys(shot_to_scene[key] for key in beat.shot_keys if key in shot_to_scene):
            beats_by_scene.setdefault(scene_key, []).append(beat.beat_id)

    unresolved = list(dict.fromkeys([*understanding.unresolved, *plan.unresolved]))
    screenplay_scenes: list[ScreenplaySceneV1] = []
    text_lines: list[str] = [snapshot.episode_title]
    emitted: set[str] = set()

    for plan_scene in plan.scenes:
        scene = scene_by_key[plan_scene.scene_key]
        heading = _scene_heading(scene)
        actions: list[ScreenplayActionV1] = []
        dialogues: list[ScreenplayDialogueV1] = []
        text_lines.extend(["", heading, f"[{_format_time(scene.start_us)}–{_format_time(scene.end_us)}]"])

        for block in plan_scene.blocks:
            if isinstance(block, ScreenplayPlanActionV1):
                action = ScreenplayActionV1(text=block.text.strip(), source_refs=list(dict.fromkeys(block.supporting_fact_refs)))
                actions.append(action)
                text_lines.append(f"[{_format_time(_ref_time(action.source_refs, snapshot))}] {action.text}")
                continue

            utterance = utterance_by_id[block.dialogue_group_id]
            if utterance.dialogue_group_id in emitted:
                raise SourceStorySkillError("canonical SourceDialogueUtterance would be emitted more than once")
            emitted.add(utterance.dialogue_group_id)
            dialogue = _dialogue_row(utterance, person_names=person_names)
            dialogues.append(dialogue)
            text_lines.extend(["", dialogue.speaker, f"[{_format_time(dialogue.start_us)}] {dialogue.text}"])

        screenplay_scenes.append(ScreenplaySceneV1(
            scene_key=scene.scene_key,
            heading=heading,
            source_refs=[f"scene:{scene.scene_key}"] + [f"shot:{shot.shot_key}" for shot in scene.shots],
            actions=actions,
            dialogue=dialogues,
            story_beat_refs=list(dict.fromkeys(beats_by_scene.get(scene.scene_key, []))),
        ))

    expected = set(dialogue_ids)
    if emitted != expected:
        raise SourceStorySkillError("screenplay did not emit every canonical SourceDialogueUtterance exactly once")
    for utterance in snapshot.source_dialogue_utterances:
        if not utterance.speakers:
            unresolved.append(f"{utterance.dialogue_group_id}:speaker-unresolved")
    unresolved = list(dict.fromkeys(unresolved))
    status = "READY_WITH_WARNINGS" if snapshot.warnings or unresolved else "READY"
    return ScreenplayReconstructionV1(
        source_revision=snapshot.source_shot_revision_id,
        source_fingerprint=snapshot.source_fingerprint,
        episode_id=snapshot.episode_id,
        skill=_skill_ref(),
        title=snapshot.episode_title,
        status=status,
        scenes=screenplay_scenes,
        screenplay_text="\n".join(text_lines).strip(),
        unresolved=unresolved,
    )


def compile_source_screenplay_v2(
    snapshot_payload: Mapping[str, Any] | SourceDramaEpisodeSnapshotV1,
    *,
    episode_understanding_provider: Callable[[str], Mapping[str, Any]] | None = None,
    screenplay_reconstruction_provider: Callable[[str], Mapping[str, Any]] | None = None,
) -> SourceScreenplayCompilationV1:
    snapshot = (
        snapshot_payload
        if isinstance(snapshot_payload, SourceDramaEpisodeSnapshotV1)
        else SourceDramaEpisodeSnapshotV1.model_validate(snapshot_payload)
    )
    shot_facts = compile_shot_facts_v1(snapshot)
    understanding = compile_episode_understanding_v1(
        snapshot,
        shot_facts,
        provider=episode_understanding_provider,
    )
    screenplay = compile_grounded_screenplay_reconstruction_v2(
        snapshot,
        shot_facts,
        understanding,
        provider=screenplay_reconstruction_provider,
    )
    skill_chain = [shot_facts.skill, understanding.skill, screenplay.skill]
    input_material = {
        "source_fingerprint": snapshot.source_fingerprint,
        "skill_chain": [item.model_dump(mode="json") for item in skill_chain],
        "reconstruction_mode": "grounded-screenplay-plan-v2",
    }
    import hashlib
    input_fingerprint = hashlib.sha256(
        json.dumps(input_material, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    output_material = {
        "input_fingerprint": input_fingerprint,
        "shot_facts": shot_facts.model_dump(mode="json"),
        "episode_understanding": understanding.model_dump(mode="json"),
        "screenplay": screenplay.model_dump(mode="json"),
    }
    output_fingerprint = hashlib.sha256(
        json.dumps(output_material, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    status = "READY_WITH_WARNINGS" if snapshot.warnings or understanding.unresolved or screenplay.unresolved else "READY"
    return SourceScreenplayCompilationV1(
        status=status,
        episode_id=snapshot.episode_id,
        source_fingerprint=snapshot.source_fingerprint,
        input_fingerprint=input_fingerprint,
        output_fingerprint=output_fingerprint,
        skill_chain=skill_chain,
        shot_facts=shot_facts,
        episode_understanding=understanding,
        screenplay=screenplay,
    )


def source_screenplay_artifact_path_v1(snapshot: SourceDramaEpisodeSnapshotV1) -> Path:
    return (
        studio_v2.episode_dir(snapshot.project_id, snapshot.episode_id)
        / "source-screenplay"
        / SOURCE_SCREENPLAY_ARTIFACT_FILENAME
    )


def persist_source_screenplay_v1(
    snapshot: SourceDramaEpisodeSnapshotV1,
    compilation: SourceScreenplayCompilationV1,
) -> Path:
    if compilation.episode_id != snapshot.episode_id or compilation.source_fingerprint != snapshot.source_fingerprint:
        raise SourceStorySkillError("source screenplay artifact does not belong to the current SourceDramaSnapshot")
    path = source_screenplay_artifact_path_v1(snapshot)
    path.parent.mkdir(parents=True, exist_ok=True)
    serialized = json.dumps(compilation.model_dump(mode="json"), ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    temp = path.with_name(path.name + ".tmp")
    temp.unlink(missing_ok=True)
    try:
        temp.write_text(serialized, encoding="utf-8")
        os.replace(temp, path)
    finally:
        temp.unlink(missing_ok=True)
    return path


def read_source_screenplay_v1(snapshot: SourceDramaEpisodeSnapshotV1) -> SourceScreenplayReadV1:
    path = source_screenplay_artifact_path_v1(snapshot)
    if not path.is_file():
        return SourceScreenplayReadV1(
            state="MISSING",
            episode_id=snapshot.episode_id,
            source_fingerprint=snapshot.source_fingerprint,
            message="当前剧集还没有生成原片还原剧本。",
        )
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        compilation = SourceScreenplayCompilationV1.model_validate(payload)
    except (OSError, json.JSONDecodeError, ValidationError) as exc:
        raise SourceStorySkillError("source screenplay artifact is invalid") from exc
    if compilation.episode_id != snapshot.episode_id or compilation.source_fingerprint != snapshot.source_fingerprint:
        return SourceScreenplayReadV1(
            state="STALE",
            episode_id=snapshot.episode_id,
            source_fingerprint=snapshot.source_fingerprint,
            message="原片事实已经变化，请重新生成原片还原剧本。",
        )
    return SourceScreenplayReadV1(
        state="READY",
        episode_id=snapshot.episode_id,
        source_fingerprint=snapshot.source_fingerprint,
        message="原片还原剧本已生成。",
        compilation=compilation,
    )


__all__ = [
    "SourceScreenplayReadV1",
    "compile_grounded_screenplay_reconstruction_v2",
    "compile_source_screenplay_v2",
    "persist_source_screenplay_v1",
    "read_source_screenplay_v1",
    "source_screenplay_artifact_path_v1",
]
